import Header from "./Components/Header";
import Providers from "./Components/Providers";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Imdb clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>

        {/* header */}
        <Header />
        {/* navbar */}

        {/* searchbox */}

        {children}
        </Providers>
      </body>
    </html>
  );
}
